apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chainlit-adk-app
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: PROJECT_NUMBER-compute@developer.gserviceaccount.com
      containers:
      - name: chainlit-app
        image: gcr.io/PROJECT_ID/chainlit-adk-app:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        # API Keys (set these via gcloud or Cloud Console)
        - name: GEMINI_API_KEY
          value: YOUR_GEMINI_API_KEY
        - name: OPENAI_API_KEY
          value: YOUR_OPENAI_API_KEY
        - name: ANTHROPIC_API_KEY
          value: YOUR_ANTHROPIC_API_KEY
        # Chainlit configuration
        - name: CHAINLIT_PORT
          value: '8000'
        - name: PYTHONUNBUFFERED
          value: '1'
        resources:
          limits:
            cpu: '1000m'
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 0
          periodSeconds: 3
          timeoutSeconds: 5
          failureThreshold: 10
